#!/usr/bin/env bash
# ============================================================
# GYDS Chain — Validator Node Setup
# Supports: Ubuntu 20.04/22.04/24.04, Debian 11/12,
#           CentOS/RHEL/Rocky/AlmaLinux 8/9, Fedora 38+
#
# Usage: sudo bash setup-validatornode-server.sh [OPTIONS]
#
# Options:
#   --datadir  DIR         Chain data directory (default: /var/lib/gyds-validatornode)
#   --keystore PATH        Path to keystore JSON file
#   --validator-key HEX    Hex private key (alternative to --keystore)
#   --p2p-port  PORT       P2P port (default: 30303)
#   --rpc-port  PORT       RPC port — localhost only (default: 8545)
#   --ssh-port  PORT       SSH port for firewall (default: 22)
#   --bootstrap-nodes STR  Comma-separated bootstrap peer addresses
#   --log-level LEVEL      trace|debug|info|warn|error (default: info)
#   --no-docker            Run as native systemd service
#   --update               Update existing installation
#   --uninstall            Remove node (preserves chain data)
#   --help                 Show this help and exit
#
# SECURITY NOTE:
#   The validator RPC is bound to 127.0.0.1 by default.
#   Do NOT expose port 8545 publicly on a validator node.
# ============================================================
set -euo pipefail

APP_NAME="gyds-validatornode"
APP_USER="gyds"
APP_DIR="/opt/gyds-validatornode"
REPO_URL="https://github.com/hc172808/validatornode.git"
BRANCH="main"
GO_VERSION="1.22.4"

GYDS_DATADIR="${GYDS_DATADIR:-/var/lib/gyds-validatornode}"
GYDS_CHAIN_ID="${GYDS_CHAIN_ID:-13370}"
GYDS_P2P_PORT="${GYDS_P2P_PORT:-30303}"
GYDS_RPC_PORT="${GYDS_RPC_PORT:-8545}"
SSH_PORT="22"
LOG_LEVEL="info"
BOOTSTRAP_NODES=""
VALIDATOR_KEY=""
KEYSTORE_PATH=""
USE_DOCKER=true
IS_UPDATE=false
UNINSTALL=false

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[VALIDATOR]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
info() { echo -e "${CYAN}[INFO]${NC} $*"; }
die()  { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

show_help() {
  cat <<EOF

GYDS Chain — Validator Node Setup
===================================

Usage: sudo bash setup-validatornode-server.sh [OPTIONS]

OPTIONS
  --datadir         DIR    Chain data directory      (default: /var/lib/gyds-validatornode)
  --keystore        PATH   Path to keystore JSON file (generated by 'gyds-validatornode keygen')
  --validator-key   HEX    Raw hex private key (alternative to --keystore)
  --p2p-port        PORT   P2P networking port        (default: 30303)
  --rpc-port        PORT   JSON-RPC port, local only  (default: 8545)
  --ssh-port        PORT   SSH port for firewall      (default: 22)
  --bootstrap-nodes STR    Comma-separated peer list  e.g. tcp://1.2.3.4:30303
  --log-level       LEVEL  trace|debug|info|warn|error (default: info)
  --no-docker              Run as native systemd service
  --update                 Update existing installation
  --uninstall              Remove node (preserves chain data)
  --help                   Show this help and exit

KEY MANAGEMENT
  Generate a new validator key:
    ./bin/gyds-validatornode keygen
    or: docker run --rm gyds-validatornode keygen

  The keygen command prints your validator address and private key hex.
  Store the private key safely — anyone with it can sign blocks as you.

SECURITY
  - RPC port 8545 is bound to 127.0.0.1 only (never public)
  - Only port 30303 (P2P) is opened in the firewall
  - Keep your private key / keystore file secure (chmod 600)
  - Never run a validator on the same machine as a public RPC node

EXAMPLES
  Fresh install with hex key:
    sudo GYDS_VALIDATOR_KEY=abc123... bash setup-validatornode-server.sh

  Fresh install with keystore file:
    sudo bash setup-validatornode-server.sh --keystore /path/to/validator.json

  With bootstrap peers:
    sudo bash setup-validatornode-server.sh \\
      --validator-key abc123... \\
      --bootstrap-nodes tcp://BOOST_IP:30306

  Update:
    sudo bash ${APP_DIR}/setup-validatornode-server.sh --update

EOF
}

[[ $EUID -ne 0 ]] && die "Run as root: sudo bash $0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --datadir)         GYDS_DATADIR="$2";     shift 2 ;;
    --keystore)        KEYSTORE_PATH="$2";    shift 2 ;;
    --validator-key)   VALIDATOR_KEY="$2";    shift 2 ;;
    --p2p-port)        GYDS_P2P_PORT="$2";    shift 2 ;;
    --rpc-port)        GYDS_RPC_PORT="$2";    shift 2 ;;
    --ssh-port)        SSH_PORT="$2";         shift 2 ;;
    --bootstrap-nodes) BOOTSTRAP_NODES="$2";  shift 2 ;;
    --log-level)       LOG_LEVEL="$2";        shift 2 ;;
    --no-docker)       USE_DOCKER=false;      shift   ;;
    --update)          IS_UPDATE=true;        shift   ;;
    --uninstall)       UNINSTALL=true;        shift   ;;
    --help|-h)         show_help; exit 0      ;;
    *) die "Unknown flag: $1" ;;
  esac
done

if $UNINSTALL; then
  log "Uninstalling GYDS validatornode..."
  systemctl stop  gyds-validatornode 2>/dev/null || true
  systemctl disable gyds-validatornode 2>/dev/null || true
  rm -f /etc/systemd/system/gyds-validatornode.service
  systemctl daemon-reload 2>/dev/null || true
  [[ -f "$APP_DIR/docker-compose.yml" ]] && \
    docker compose -f "$APP_DIR/docker-compose.yml" down --remove-orphans 2>/dev/null || true
  rm -rf "$APP_DIR"
  log "Uninstall complete. Chain data at ${GYDS_DATADIR} was preserved."
  exit 0
fi

if [[ -z "$VALIDATOR_KEY" && -z "$KEYSTORE_PATH" ]]; then
  warn "No validator key provided."
  warn "  Run 'gyds-validatornode keygen' to generate one, then pass:"
  warn "    --validator-key HEX    or    --keystore /path/to/file.json"
  warn "Continuing setup without a key — set GYDS_VALIDATOR_KEY in .env before starting."
fi

if ! command -v docker &>/dev/null && $USE_DOCKER; then
  log "Installing Docker..."
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y --no-install-recommends ca-certificates curl gnupg lsb-release
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
fi

if ! id "$APP_USER" &>/dev/null; then
  useradd --system --no-create-home --shell /usr/sbin/nologin "$APP_USER" \
    || adduser --system --no-create-home "$APP_USER"
fi
$USE_DOCKER && command -v docker &>/dev/null && usermod -aG docker "$APP_USER" || true

log "Configuring firewall..."
if command -v ufw &>/dev/null; then
  ufw default deny incoming 2>/dev/null || true
  ufw default allow outgoing 2>/dev/null || true
  ufw allow "$SSH_PORT"/tcp        comment "SSH"
  ufw allow "$GYDS_P2P_PORT"/tcp   comment "GYDS P2P"
  ufw allow "$GYDS_P2P_PORT"/udp   comment "GYDS P2P UDP"
  ufw deny  "$GYDS_RPC_PORT"/tcp   comment "Validator RPC (localhost only)"
  ufw --force enable
  log "Firewall: P2P open, RPC blocked externally."
fi

mkdir -p "$APP_DIR"
if [ ! -d "$APP_DIR/.git" ]; then
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR" || \
    { warn "Could not clone repo — place files in $APP_DIR manually"; mkdir -p "$APP_DIR"; }
else
  git -C "$APP_DIR" fetch origin
  git -C "$APP_DIR" reset --hard "origin/$BRANCH"
fi
chown -R "${APP_USER}:${APP_USER}" "$APP_DIR"

ENV_FILE="${APP_DIR}/.env"
if [[ ! -f "$ENV_FILE" ]] || $IS_UPDATE; then
  cat > "$ENV_FILE" <<ENV
GYDS_CHAIN_ID=${GYDS_CHAIN_ID}
GYDS_NODE_MODE=validator
GYDS_RPC_PORT=${GYDS_RPC_PORT}
GYDS_RPC_HOST=127.0.0.1
GYDS_P2P_PORT=${GYDS_P2P_PORT}
GYDS_DATA_DIR=/app/data
GYDS_LOG_LEVEL=${LOG_LEVEL}
$([ -n "$VALIDATOR_KEY"    ] && echo "GYDS_VALIDATOR_KEY=${VALIDATOR_KEY}")
$([ -n "$KEYSTORE_PATH"    ] && echo "GYDS_KEYSTORE_PATH=${KEYSTORE_PATH}")
$([ -n "$BOOTSTRAP_NODES"  ] && echo "GYDS_BOOTSTRAP_NODES=${BOOTSTRAP_NODES}")
ENV
  chmod 600 "$ENV_FILE"
  chown "${APP_USER}:${APP_USER}" "$ENV_FILE"
fi

mkdir -p "${GYDS_DATADIR}"/{keystore,logs}
chown -R "${APP_USER}:${APP_USER}" "$GYDS_DATADIR"

if $USE_DOCKER; then
  cd "$APP_DIR"
  docker compose down --remove-orphans 2>/dev/null || true
  docker compose build --no-cache
  docker compose up -d
  log "Validator node started via Docker."
else
  export PATH="${PATH}:/usr/local/go/bin"
  if ! command -v go &>/dev/null; then
    ARCH=$(dpkg --print-architecture 2>/dev/null || echo amd64)
    wget -q "https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz" -O /tmp/go.tar.gz
    rm -rf /usr/local/go
    tar -C /usr/local -xzf /tmp/go.tar.gz
    rm /tmp/go.tar.gz
  fi
  cd "$APP_DIR" && go build -o bin/gyds-validatornode .
  cat > /etc/systemd/system/gyds-validatornode.service <<SVC
[Unit]
Description=GYDS Validator Node
After=network-online.target
Wants=network-online.target

[Service]
User=${APP_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${APP_DIR}/bin/gyds-validatornode start
Restart=always
RestartSec=5s
LimitNOFILE=65536
StandardOutput=append:${GYDS_DATADIR}/logs/validator.log
StandardError=append:${GYDS_DATADIR}/logs/validator-error.log

[Install]
WantedBy=multi-user.target
SVC
  systemctl daemon-reload
  systemctl enable --now gyds-validatornode
  log "Validator node started via systemd."
fi

SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "YOUR_SERVER_IP")

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        GYDS VALIDATOR NODE DEPLOYED              ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo "  Chain ID   : ${GYDS_CHAIN_ID}"
echo "  P2P        : tcp://${SERVER_IP}:${GYDS_P2P_PORT}  (open)"
echo "  RPC        : http://127.0.0.1:${GYDS_RPC_PORT}   (localhost only)"
echo ""
echo "  ── Security reminder ─────────────────────────────"
echo "  - RPC port ${GYDS_RPC_PORT} is NOT exposed publicly"
echo "  - Keep your private key / keystore file secure"
echo "  - Back up ${GYDS_DATADIR}/keystore/"
echo ""
if $USE_DOCKER; then
echo "  ── Management ───────────────────────────────────"
echo "  Logs   : cd ${APP_DIR} && docker compose logs -f"
echo "  Status : docker compose ps"
echo "  Restart: docker compose restart"
else
echo "  ── Management ───────────────────────────────────"
echo "  Logs   : journalctl -u gyds-validatornode -f"
echo "  Status : systemctl status gyds-validatornode"
echo "  Restart: systemctl restart gyds-validatornode"
fi
echo ""
echo "  Update : sudo bash ${APP_DIR}/setup-validatornode-server.sh --update"
echo ""
