#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════
#  GYDS Chain — Validator Node  /  WireGuard Client Setup
#
#  The validator node is HIGH VALUE. After WireGuard is set up,
#  port 8545 (RPC) is accessible ONLY over the VPN tunnel.
#  The firewall blocks 8545 from the public internet entirely.
#
#  Usage:
#    sudo bash setup-wireguard.sh [options]
#
#  Options:
#    --server-pubkey KEY        Server public key (required)
#    --server-endpoint IP:PORT  e.g. 1.2.3.4:51820 (required)
#    --client-vpn-ip IP/CIDR    This node's VPN IP (default: 10.8.0.3/32)
#    --vpn-subnet CIDR          VPN subnet (default: 10.8.0.0/24)
#    --wg-port PORT             WireGuard port (default: 51820)
#    --status | --down | --up | --show-pubkey
# ══════════════════════════════════════════════════════════════
set -euo pipefail

WG_IFACE="wg0"
WG_PORT="${WG_PORT:-51820}"
SERVER_PUBKEY="${SERVER_PUBKEY:-}"
SERVER_ENDPOINT="${SERVER_ENDPOINT:-}"
CLIENT_VPN_IP="${CLIENT_VPN_IP:-10.8.0.3/32}"
VPN_SUBNET="${VPN_SUBNET:-10.8.0.0/24}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

while [[ $# -gt 0 ]]; do
  case $1 in
    --server-pubkey)   SERVER_PUBKEY="$2";   shift 2 ;;
    --server-endpoint) SERVER_ENDPOINT="$2"; shift 2 ;;
    --client-vpn-ip)   CLIENT_VPN_IP="$2";   shift 2 ;;
    --vpn-subnet)      VPN_SUBNET="$2";      shift 2 ;;
    --wg-port)         WG_PORT="$2";         shift 2 ;;
    --status)   wg show; exit 0 ;;
    --down)     wg-quick down "$WG_IFACE" 2>/dev/null || true; echo "wg0 down"; exit 0 ;;
    --up)       wg-quick up   "$WG_IFACE" 2>/dev/null || true; echo "wg0 up";   exit 0 ;;
    --show-pubkey)
      [[ -f /etc/wireguard/privatekey ]] && wg pubkey < /etc/wireguard/privatekey || echo "Run setup first"
      exit 0 ;;
    *) shift ;;
  esac
done

log()  { echo "[$(date '+%H:%M:%S')] $*"; }
warn() { echo "[$(date '+%H:%M:%S')] WARNING: $*" >&2; }
err()  { echo "[$(date '+%H:%M:%S')] ERROR: $*" >&2; exit 1; }

[[ $EUID -ne 0 ]] && err "Run as root: sudo bash $0"

if [[ -z "$SERVER_PUBKEY" ]]; then
  read -rp "  WireGuard server public key: " SERVER_PUBKEY
fi
if [[ -z "$SERVER_ENDPOINT" ]]; then
  read -rp "  WireGuard server endpoint (IP:PORT): " SERVER_ENDPOINT
fi
if [[ -z "$CLIENT_VPN_IP" ]]; then
  read -rp "  This node's VPN IP [10.8.0.3/32]: " inp
  CLIENT_VPN_IP="${inp:-10.8.0.3/32}"
fi

[[ -z "$SERVER_PUBKEY"   ]] && err "Server public key required"
[[ -z "$SERVER_ENDPOINT" ]] && err "Server endpoint required"

# ── 1. Install WireGuard ─────────────────────────────────────
log "Installing WireGuard..."
if ! command -v wg &>/dev/null; then
  if command -v apt-get &>/dev/null; then
    apt-get update -qq && apt-get install -y wireguard wireguard-tools resolvconf
  elif command -v dnf &>/dev/null; then
    dnf install -y wireguard-tools
  elif command -v yum &>/dev/null; then
    yum install -y epel-release && yum install -y wireguard-tools
  else
    err "Unsupported OS — install wireguard-tools manually."
  fi
fi

# ── 2. Generate key pair ─────────────────────────────────────
mkdir -p /etc/wireguard
chmod 700 /etc/wireguard

KEY_FILE="/etc/wireguard/privatekey"
PUB_FILE="/etc/wireguard/publickey"

if [[ ! -f "$KEY_FILE" ]]; then
  wg genkey | tee "$KEY_FILE" | wg pubkey > "$PUB_FILE"
  chmod 600 "$KEY_FILE"
  log "Generated new WireGuard key pair."
else
  wg pubkey < "$KEY_FILE" > "$PUB_FILE"
  log "Reusing existing WireGuard private key."
fi

PRIVATE_KEY=$(cat "$KEY_FILE")
PUBLIC_KEY=$(cat "$PUB_FILE")

# ── 3. Write wg0.conf ────────────────────────────────────────
# NOTE: validator routes only VPN subnet through tunnel.
# All P2P traffic stays on the public internet.
CONF_FILE="/etc/wireguard/${WG_IFACE}.conf"
cat > "$CONF_FILE" <<WGCONF
# ── GYDS Chain Validator Node — WireGuard Client ────────────
# Generated by setup-wireguard.sh on $(date)
# IMPORTANT: RPC port 8545 is accessible ONLY over this VPN.

[Interface]
PrivateKey = ${PRIVATE_KEY}
Address    = ${CLIENT_VPN_IP}
ListenPort = ${WG_PORT}

# Allow RPC access over the VPN interface only
PostUp   = ufw allow in on ${WG_IFACE} to any port 8545 proto tcp comment "Validator RPC via VPN"
PostDown = ufw delete allow in on ${WG_IFACE} to any port 8545 proto tcp 2>/dev/null; true

[Peer]
# WireGuard server
PublicKey  = ${SERVER_PUBKEY}
Endpoint   = ${SERVER_ENDPOINT}
AllowedIPs = ${VPN_SUBNET}

# Keepalive — essential for validator to maintain persistent connection
PersistentKeepalive = 15
WGCONF

chmod 600 "$CONF_FILE"
log "Wrote ${CONF_FILE}"

# ── 4. Copy template ─────────────────────────────────────────
mkdir -p "${SCRIPT_DIR}/wireguard"
cat > "${SCRIPT_DIR}/wireguard/wg0.conf.template" <<'TMPL'
# ── GYDS Chain Validator Node — WireGuard Client template ───
# Fill in your values and copy to /etc/wireguard/wg0.conf

[Interface]
PrivateKey = <GENERATED_ON_SERVER>
Address    = 10.8.0.3/32
ListenPort = 51820

PostUp   = ufw allow in on wg0 to any port 8545 proto tcp comment "Validator RPC via VPN"
PostDown = ufw delete allow in on wg0 to any port 8545 proto tcp 2>/dev/null; true

[Peer]
PublicKey  = <YOUR_SERVER_PUBLIC_KEY>
Endpoint   = <YOUR_SERVER_IP>:51820
AllowedIPs = 10.8.0.0/24
PersistentKeepalive = 15
TMPL

# ── 5. UFW: open WireGuard port ──────────────────────────────
if command -v ufw &>/dev/null; then
  ufw allow "${WG_PORT}"/udp comment "WireGuard VPN"
  # Explicitly re-deny 8545 from internet (belt + suspenders)
  ufw deny 8545/tcp comment "Validator RPC — VPN only"
  log "UFW: WireGuard port opened, RPC blocked from internet."
fi

# ── 6. Enable + start ────────────────────────────────────────
systemctl enable "wg-quick@${WG_IFACE}"
wg-quick down "${WG_IFACE}" 2>/dev/null || true
wg-quick up   "${WG_IFACE}"
sleep 2

log "WireGuard status:"
wg show

# ── 7. Summary ───────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║   GYDS Validator Node — WireGuard Client Ready       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  This node's VPN IP : ${CLIENT_VPN_IP}"
echo "  Server endpoint    : ${SERVER_ENDPOINT}"
echo ""
echo "  SECURITY: Port 8545 is now accessible ONLY over VPN"
echo "  Connect to RPC from your VPN server: ${CLIENT_VPN_IP%/*}:8545"
echo ""
echo "  ┌─ ADD THIS TO YOUR WIREGUARD SERVER ────────────────┐"
echo "  │                                                     │"
echo "  │  [Peer]                                             │"
echo "  │  # GYDS validatornode                               │"
echo "  │  PublicKey  = ${PUBLIC_KEY}"
echo "  │  AllowedIPs = ${CLIENT_VPN_IP}             │"
echo "  │                                                     │"
echo "  └─────────────────────────────────────────────────────┘"
echo ""
echo "  Commands:"
echo "    sudo wg show"
echo "    sudo bash setup-wireguard.sh --status"
echo "    sudo bash setup-wireguard.sh --show-pubkey"
